"""Public package interface for cpp-header-guard."""

from __future__ import annotations

from .cli import CLI, Arguments, main, parse_args
from .core import (
    DEFAULT_SPACES_BETWEEN_ENDIF_AND_COMMENT,
    HEADER_SUFFIXES,
    apply_guard,
    build_guard,
    clean_part,
    comment_prefix,
    ensure_guard,
    ensure_valid_start,
    find_git_dir,
    guard_define_and_end,
    guard_end_index,
    guard_name_from_define,
    guard_name_from_ifndef,
    header_guard_name,
    is_header,
    is_pragma_once,
    locate_repo_root,
    macro_guard_define_index,
    matches_endif,
    next_code_index,
    process_paths,
    remove_guard_lines,
    remove_guard_segments,
    strip_macro_guard,
    write_if_changed,
)

__all__ = [
    "Arguments",
    "CLI",
    "DEFAULT_SPACES_BETWEEN_ENDIF_AND_COMMENT",
    "HEADER_SUFFIXES",
    "apply_guard",
    "build_guard",
    "clean_part",
    "comment_prefix",
    "ensure_guard",
    "ensure_valid_start",
    "find_git_dir",
    "guard_define_and_end",
    "guard_end_index",
    "guard_name_from_define",
    "guard_name_from_ifndef",
    "header_guard_name",
    "is_header",
    "is_pragma_once",
    "locate_repo_root",
    "main",
    "macro_guard_define_index",
    "matches_endif",
    "next_code_index",
    "parse_args",
    "process_paths",
    "remove_guard_lines",
    "remove_guard_segments",
    "strip_macro_guard",
    "write_if_changed",
]
